import csv

# Target Company Research Data (Pune Region)
data = [
    ['Innovassynth Technologies', 'innovassynth.com', 'Pune', 'Custom synthesis & specialty chemicals', 'Protected nucleosides, phosphoramidites, specialty chemicals for life sciences', 'Rs.100-300Cr', 'Dr. Hardik Joshipura', 'MD & CEO', 'PhD, extensive scientific leadership', 'Strong', 'Manufacturing facility in Khopoli, Maharashtra. Dedicated blocks for oligonucleotides and specialty chemicals.', 'Strong', 'HQ and manufacturing near Pune, India.', 'Strong', 'Custom synthesis of nucleosides and phosphoramidites. Niche and high-barrier chemistry. Supplies to global pharma.', 'Strong', 'MD & CEO holds a PhD. Leadership team comprises experienced scientists.', 'Strong', 'CDMO and specialty chemicals tailwind. China+1 supply chain diversification.', 'Strong', 'Expanding nucleoside manufacturing capacity. Actively hiring on LinkedIn. Signals met: Facility + Hiring.', 100, 'A — Strong Federer', 'Strong Pass', 'High-end chemistry, strong scientific leadership, clear growth trajectory in the CDMO space.', 'Expanding nucleoside manufacturing capacity at Khopoli to meet global oligonucleotide demand.', 'innovassynth.com; MCA; LinkedIn'],
    ['Mylab Discovery Solutions', 'mylabdiscoverysolutions.com', 'Pune', 'Specialty diagnostics', 'RT-PCR kits, rapid antigen tests, molecular diagnostic automation platforms', 'Rs.100-300Cr', 'Hasmukh Rawal', 'MD', 'Post-graduate in biotechnology', 'Strong', 'In-house manufacturing of diagnostic kits and automated platforms in Pune.', 'Strong', 'HQ and manufacturing in Pune.', 'Strong', 'First Indian company to develop indigenous RT-PCR kit. Strong IP in molecular diagnostics.', 'Strong', 'Founder is a biotechnologist. Strong R&D focus.', 'Strong', 'Diagnostics manufacturing pushed by Make-in-India. Rising domestic healthcare demand.', 'Moderate', 'Post-COVID revenue stabilized, but expanding into TB and HIV testing. Signals met: Certifications.', 90, 'A — Strong Federer', 'Strong Pass', 'Pioneer in Indian molecular diagnostics with strong in-house IP and manufacturing.', 'Transitioning from COVID-19 success to building comprehensive molecular diagnostic solutions for TB and HIV.', 'mylabdiscoverysolutions.com; News articles'],
    ['Biorad Medisys', 'bioradmedisys.com', 'Pune', 'Medical devices', 'Orthopedic implants, urology disposables, surgical devices', 'Rs.50-100Cr', 'Jitendra Hegde', 'MD', '30+ years in medical devices', 'Strong', 'Manufacturing units in Pune and Bangalore. In-house production of implants.', 'Strong', 'HQ in Pune.', 'Strong', 'CE certified products. Strong export presence. Patented orthopedic solutions.', 'Moderate', 'Experienced industry veteran, but specific advanced scientific degree not clearly visible.', 'Strong', 'Medical device PLI scheme and Make-in-India tailwinds.', 'Moderate', 'Consistent export growth, visible hiring. Signals met: Hiring.', 80, 'A — Strong Federer', 'Pass', 'Solid mid-sized medical device manufacturer benefiting from import substitution.', 'Expanding your CE-certified orthopedic implant portfolio in European markets.', 'bioradmedisys.com'],
    ['BioEra Life Sciences', 'bioeralife.com', 'Pune', 'Specialty diagnostics & life-science tools', 'Automated DNA/RNA extraction systems, lab instruments, biotech educational kits', '<Rs.50Cr', 'Dr. Sameer Chaudhari', 'Founder & Director', 'PhD in Biotechnology', 'Strong', 'In-house assembly and production of biotech instruments.', 'Strong', 'HQ in Pune.', 'Moderate', 'Instruments and kits are specialized but face stiff competition from global brands.', 'Strong', 'Founder holds a PhD in Biotechnology.', 'Strong', 'Biotech research and education sector is growing.', 'Weak', 'Limited visible growth signals or capacity expansion in recent years. Signals met: 0.', 65, 'B — Probable Federer', 'Borderline', 'Technically sound founder but small scale and limited growth signals. Worth tracking.', 'Building indigenous DNA extraction platforms to replace expensive imported equipment in Indian labs.', 'bioeralife.com; LinkedIn'],
    ['Melzer Chemicals', 'melzerspeciality.com', 'Pune', 'Performance chemicals', 'Biocides, defoamers, specialty polymers for water treatment and paper industry', 'Rs.50-100Cr', 'Aniruddha Kulkarni', 'MD', 'Chemical Engineer', 'Strong', 'Manufacturing facility in Pune.', 'Strong', 'HQ in Pune.', 'Moderate', 'Specialized formulations, but not heavily patented chemistry.', 'Strong', 'Chemical engineering background.', 'Moderate', 'Water treatment and specialty coatings growing steadily.', 'Moderate', 'Visible hiring for R&D and sales. Signals met: Hiring.', 72.5, 'B — Probable Federer', 'Pass', 'Solid performance chemical MSME with engineering leadership.', 'Developing eco-friendly biocides for the growing water treatment and paper manufacturing sectors.', 'melzerspeciality.com'],
    ['Chemion Speciality Chemicals', 'chemionsc.in', 'Pune', 'Performance chemicals', 'RO antiscalants, boiler chemicals, cooling water treatment chemicals', '<Rs.50Cr', 'Sameer Bapat', 'Founder', 'B.E. Chemical', 'Strong', 'Manufacturing plant in Pune.', 'Strong', 'HQ in Pune.', 'Moderate', 'Formulation-based products, less complex than custom synthesis.', 'Strong', 'Chemical engineering founder.', 'Moderate', 'Industrial water treatment is a stable, growing sector.', 'Weak', 'Small scale, no major expansion news. Signals met: 0.', 65, 'B — Probable Federer', 'Borderline', 'Good technical fit but lacks strong growth or differentiation signals.', 'Providing customized cooling water and boiler treatment formulations for local MSME manufacturers.', 'chemionsc.in'],
    ['Seagull BioSolutions', 'seagullbiosolutions.in', 'Pune', 'Specialty biotech', 'Viral vectors, diagnostic antigens, vaccine technologies', '<Rs.50Cr', 'Dr. Vishwas D. Joshi', 'Founder & CEO', 'PhD, ex-NIV, strong scientific background', 'Moderate', 'Focuses heavily on R&D, small-scale production.', 'Strong', 'HQ in Pune (NCL Innovation Park).', 'Strong', 'Proprietary active virosome technology (e-ASV).', 'Strong', 'Highly credentialed scientist founder.', 'Strong', 'Vaccine technology and biotech tailwinds.', 'Weak', 'Still largely in R&D and early commercialization phase. Pre-revenue/low-revenue. Signals met: 0.', 70, 'B — Probable Federer', 'Pass', 'Deep IP and strong founder, but scale is still small.', 'Developing proprietary e-ASV technology to revolutionize vaccine delivery and diagnostics.', 'seagullbiosolutions.in'],
    ['Polybond India Pvt Ltd', 'polybondindia.com', 'Pune', 'Performance chemicals', 'Anti-vibration mounts, silicone hoses, molded rubber parts', 'Rs.300-500Cr', 'Adit Rathi', 'MD', 'Gen-2, engineering background', 'Strong', 'Multiple manufacturing plants in Pune.', 'Strong', 'HQ in Pune.', 'Moderate', 'Tier-1 auto supplier, high quality but standard products.', 'Moderate', 'Gen-2 leadership, process-oriented.', 'Moderate', 'Auto component sector growing steadily.', 'Strong', 'Expanding globally, setting up new plants. Signals met: Facility + Financial.', 70, 'B — Probable Federer', 'Pass', 'Large, process-driven manufacturer, slightly borderline on differentiation.', 'Scaling global exports of specialized silicone hoses and NVH solutions.', 'polybondindia.com'],
    ['Nichrome India', 'nichrome.com', 'Pune', 'Industrial sensors & instrumentation', 'Automated packaging machines, filling systems', 'Rs.100-300Cr', 'Hemant Joshi', 'MD', 'Engineer', 'Strong', 'Large manufacturing facility in Pune.', 'Strong', 'HQ in Pune.', 'Strong', 'Pioneer in Indian packaging machinery. Strong design capabilities.', 'Strong', 'Engineering-led organization.', 'Strong', 'FMCG and pharma packaging automation tailwinds.', 'Moderate', 'Steady growth, regular new product launches. Signals met: Hiring.', 85, 'A — Strong Federer', 'Strong Pass', 'Market leader in domestic packaging automation, solid engineering.', 'Pioneering high-speed automated packaging lines for the Indian FMCG sector.', 'nichrome.com'],
    ['Accurate Engineering Company', 'accurate.co.in', 'Pune', 'Industrial sensors & instrumentation', '3D coordinate measuring machines (CMM), precision gauges', 'Rs.50-100Cr', 'Vikram Salunkhe', 'MD', 'Engineering background', 'Strong', 'In-house manufacturing of precision instruments in Pune.', 'Strong', 'HQ in Pune.', 'Strong', 'High precision metrology equipment, replacing imports.', 'Strong', 'Engineering leadership, deep metrology expertise.', 'Strong', 'Make-in-India driving demand for quality control equipment.', 'Moderate', 'Established player, steady market share. Signals met: Certifications.', 85, 'A — Strong Federer', 'Strong Pass', 'Deep technical capability in metrology.', 'Providing indigenous 3D CMM solutions to Indian aerospace and defence sectors.', 'accurate.co.in'],
    ['Yashashri Polymers', 'yashashripolymers.com', 'Pune', 'Performance chemicals', 'Plasticizer-free PVC compounds, specialty polymer blends', '<Rs.50Cr', 'Rahul Deshpande', 'Director', 'Polymer Engineer', 'Strong', 'Manufacturing plant in Pune.', 'Strong', 'HQ in Pune.', 'Moderate', 'Specialty compounds for medical and food-grade applications.', 'Strong', 'Polymer engineering background.', 'Moderate', 'Medical and food packaging growth.', 'Weak', 'No major expansion signals. Signals met: 0.', 65, 'B — Probable Federer', 'Borderline', 'Technical founder, but small and slow growing.', 'Formulating specialized, non-toxic PVC compounds for critical medical device packaging.', 'yashashripolymers.com'],
    ['Praj Industries', 'praj.net', 'Pune', 'Specialty biotech', 'Bioenergy, engineering systems', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified on revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Strong', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Revenue exceeds Rs.3000Cr. Outgrown ICP.', '-', 'praj.net; BSE filings'],
    ['Clean Science and Technology', 'cleanscience.co.in', 'Pune', 'Specialty chemicals', 'Performance chemicals', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified on revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Strong', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Revenue ~Rs.900Cr. Highly successful listed company, but outgrown ICP.', '-', 'cleanscience.co.in'],
    ['Sudarshan Chemical Industries', 'sudarshan.com', 'Pune', 'Performance chemicals', 'Pigments, dyes', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified on revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Strong', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Revenue > Rs.2000Cr. Outgrown ICP.', '-', 'sudarshan.com'],
    ['Serum Institute of India', 'seruminstitute.com', 'Pune', 'Specialty biotech', 'Vaccines', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified on revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Strong', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'World largest vaccine manufacturer. Multi-billion dollar revenue.', '-', 'seruminstitute.com'],
    ['Krsnaa Diagnostics', 'krsnaadiagnostics.com', 'Pune', 'Specialty diagnostics', 'Diagnostic testing services', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Service company.', 'Fail', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Diagnostic lab chain, not a manufacturer of diagnostic equipment.', '-', 'krsnaadiagnostics.com'],
    ['GeneOmbio Technologies', 'geneombiotechnologies.com', 'Pune', 'Contract research', 'Genomic testing services', '<Rs.50Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Service company.', 'Fail', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'CRO providing genomic testing and analysis services. No product manufacturing.', '-', 'geneombiotechnologies.com'],
    ['Enzene Biosciences', 'enzene.com', 'Pune', 'Specialty biotech', 'Biosimilars', 'Rs.100-300Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Subsidiary of Alkem Labs.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Subsidiary of Alkem Laboratories. Not an independent promoter-driven company.', '-', 'enzene.com'],
    ['Thermax', 'thermaxglobal.com', 'Pune', 'Industrial sensors & instrumentation', 'Energy and environment engineering', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified on revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Strong', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Revenue > Rs.8000Cr. Outgrown ICP.', '-', 'thermaxglobal.com'],
    ['Forbes Marshall', 'forbesmarshall.com', 'Pune', 'Industrial sensors & instrumentation', 'Steam engineering and control instrumentation', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified on revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Strong', '-', 'Strong', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Revenue > Rs.1500Cr. Outgrown ICP.', '-', 'forbesmarshall.com'],
    ['Cotmac Electronics', 'cotmac.io', 'Pune', 'Industrial sensors & instrumentation', 'Industrial automation solutions', 'Rs.100-300Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Service company.', 'Fail', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Provides industrial automation solutions and system integration services, not an OEM manufacturer.', '-', 'cotmac.io'],
    ['Renishaw India', 'renishaw.com', 'Pune', 'Industrial sensors & instrumentation', 'Precision measurement and healthcare', 'Rs.100-300Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Foreign subsidiary.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Subsidiary of UK-based Renishaw plc. Not an independent Indian MSME.', '-', 'renishaw.com'],
    ['Hella India Automotive', 'hella.com', 'Pune', 'Performance chemicals', 'Auto components', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Foreign subsidiary.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Subsidiary of Forvia/Hella. Not independent.', '-', 'hella.com'],
    ['Emcure Pharmaceuticals', 'emcure.com', 'Pune', 'Complex APIs & regulated pharma', 'Pharma', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Revenue and PE backed.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Revenue > Rs.6000Cr, backed by Bain Capital. Outgrown ICP.', '-', 'emcure.com'],
    ['Lupin', 'lupin.com', 'Pune', 'Complex APIs & regulated pharma', 'Pharma', '>Rs.500Cr', '-', '-', '-', 'Not evaluated — auto-disqualified. Revenue.', 'Strong', '-', 'Strong', '-', 'Not scored', '-', 'Not scored', '-', 'Not scored', '-', '0', 'D — Auto-disqualify', 'Fail — Auto-disqualify', 'Large cap pharma major. Outgrown ICP.', '-', 'lupin.com']
]

headers = [
    'Company Name', 'Website', 'City', 'Segment', 'What They Make', 'Revenue Band', 'Decision Maker', 'DM Title', 'DM Background',
    'C1 Manufacturer Score', 'C1 Evidence', 'C2 India Score', 'C2 Evidence', 'C3 Differentiation Score', 'C3 Evidence',
    'C4 Tech DM Score', 'C4 Evidence', 'C5 Tailwind Score', 'C5 Evidence', 'C6 Growth Score', 'C6 Evidence',
    'Federer Score', 'Score Band', 'Verdict', 'Verdict Reasoning', 'Personalization Hook', 'Evidence Sources'
]

if __name__ == '__main__':
    with open('part_a_output.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        for row in data:
            writer.writerow(row)
    print('Generated part_a_output.csv with 25 scored companies.')
